#!/bin/bash

. $(dirname $0)/init_homalg-project_test_suite

cd $PKG_PATH

L="MapleForHomalg.g D-Modules.g ExamplesForHomalg.g GradedModules.g Sheaves.g RingsForHomalg.g"

exec 3>&1

for i in $L; do
  {
  echo -e "\n"
  echo -e "\033[1;33;41m"
  echo "~~~~~~~~~~~~~~~~~~~~~~~~~"
  echo -e "\033[0m"
  echo $i
  echo -e "\033[1;33;41m"
  echo "~~~~~~~~~~~~~~~~~~~~~~~~~"
  echo -e "\033[0m"
  } >&2
  sh -c "$BIN_PATH/${i}"
done

echo -e "\a\a\a"
