#!/bin/bash

. $(dirname $0)/init_homalg_project_test_suite

cd $PKG_PATH

{
    echo -e "\n"
    echo -e "\033[1;33;40m"
    echo "========================="
    echo -e "\033[0m"
    echo "LoadPackage( \"Sheaves\" );"
    echo -e "\033[1;33;40m"
    echo "========================="
    echo -e "\033[0m"
} >&2

gap "${BIN_PATH}/LoadSheaves.g" < /dev/null

. ./MapleForHomalg/bin/LibraryPath.sh

{
    echo -e "\n"
    echo -e "\033[1;33;40m"
    echo "========================="
    echo -e "\033[0m"
    echo "LoadAllPackages( );"
    echo -e "\033[1;33;40m"
    echo "========================="
    echo -e "\033[0m"
} >&2

gap "${BIN_PATH}/LoadAllPackages.g" < /dev/null

unset DYLD_LIBRARY_PATH
unset LD_LIBRARY_PATH

L="homalg_project/RingsForHomalg homalg_project/MatricesForHomalg homalg_project/HomalgToCAS VirtualCAS homalg_project/IO_ForHomalg homalg_project/Gauss homalg_project/GaussForHomalg homalg_project/SCO alexander Conley SimplicialObjects Orbifolds homalg_project/LocalizeRingForHomalg homalg_project/GradedRingForHomalg k-Points AbelianSystems homalg_project/homalg homalg_project/Modules SystemTheory Sheaves D-Modules homalg_project/ExamplesForHomalg homalg_project/GradedModules"

for i in $L; do
  {
  echo -e "\n"
  echo -e "\033[1;33;40m"
  echo "========================="
  echo -e "\033[0m"
  echo $i
  echo -e "\033[1;33;40m"
  echo "========================="
  echo -e "\033[0m"
  } >&2
  cd $i
  make test < /dev/null
  cd $PKG_PATH
done

echo -e "\n"
